# Generated by Django 6.0 on 2025-12-19 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_code', models.CharField(max_length=64, unique=True)),
                ('user_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_code', to='core_app.profileuser')),
            ],
            options={
                'verbose_name': 'Authentication Code',
                'verbose_name_plural': 'Authentication Codes',
                'db_table': 'authentication_codes',
            },
        ),
    ]
